latex author: $AUTHOR
latex title: $TITLE
my abstract: $ABSTRACT
bibtex: $BIBTEX
my style: $MYSTYLE
my color: $MYCOLOR
my address: $MYADDRESS
my mobile: $MYMOBILE
my fixed: $MYFIXED
my email: $MYEMAIL
my linkedin: $MYLINKEDIN
my github: $MYGITHUB
latex input: $TEMPLATE/setup.tex
latex footer: $TEMPLATE/footer.tex
